name: Deployment pipeline

env:
  ON_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}
  COMMIT_URL: https://github.com/JG-0204/full-stack-open-pokedex/commit/${{ github.sha }}

on:
  schedule:
    - cron: '30 16 1 12 0'
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      # - name: test
      #   run: npm test
      # - name: Install playwright browsers
      #   run: npx playwright install --with-deps
      # - name: End-to-End test
      #   run: npm run test:e2e
      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
      # - name: Trigger deployment
      #   if: ${{ github.event_name == 'push' && env.ON_SKIP == 'false' }}
      #   run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      # - name: On deployment failure
      #   if: ${{ failure() }}
      #   uses: sarisia/actions-status-discord@33dfe58bd6a779c49926a82a2c008bab1ca733ee
      #   with:
      #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
      #     username: 'FSOPokedex'
      #     title: 'Build failed'
      #     nodetail: true
      #     status: 'failure'
      #     description: Commit ${{ env.COMMIT_URL }} by ${{ github.actor }} broke the build.
      #     content: 'Something went wrong'


    # tag_release:
    #   needs: simple_deployment_pipeline
    #   runs-on: ubuntu-20.04
    #   steps:
    #     - uses: actions/checkout@v4
    #     - name: Bump version and push tag
    #       if: ${{ github.event_name == 'push' && env.ON_SKIP == 'false' }}
    #       uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
    #       env:
    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #         DEFAULT_BUMP: patch

    # on_deployment_success:
    #   needs: simple_deployment_pipeline
    #   runs-on: ubuntu-20.04
    #   steps:
    #     - uses: actions/checkout@v4
    #     - name: On deployment success
    #       if: ${{ !failure() && env.ON_SKIP == 'false'}}
    #       uses: sarisia/actions-status-discord@33dfe58bd6a779c49926a82a2c008bab1ca733ee
    #       with:
    #         webhook: ${{ secrets.DISCORD_WEBHOOK }}
    #         title: 'Build success'
    #         username: 'FSOPokedex'
    #         nodetail: true
    #         status: 'success'
    #         description: New version of Pokedex deployed on [here](https://full-stack-open-pokedex-e0i8.onrender.com/) by ${{ github.actor }}
    #         content: 'Deployment successful.'
   

    health_check:
      needs: simple_deployment_pipeline
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v4
        - name: Health Check
        if: ${{ github.event.schedule == '30 16 1 12 0' }}
        uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
        with:
          url: https://full-stack-open-pokedex-e0i8.onrender.com/health
          max-attemps: 3
      - name: On health check failure
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@33dfe58bd6a779c49926a82a2c008bab1ca733ee
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'FSOPokedex'
          title: 'Health check information'
          nodetail: true
          status: 'failure'
          description: 'Health check failed'
          content: 'FSOPokedex health check'
      - name: On health check success
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@33dfe58bd6a779c49926a82a2c008bab1ca733ee
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'FSOPokedex'
          title: 'Health check information'
          nodetail: true
          status: 'success'
          description: 'Health check passed'
          content: 'FSOPokedex health check (test, should run at 16:30)'
